name: Mirror Code to Codeberg

on:
  push: 
    branches:
      - "**"

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for mirroring

      - name: Mirror to Codeberg
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/kkkfasya/notnix'
          GIT_USERNAME: kkkfasya
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
